### ISSUE TITLE
BulkInsert - Error Cannot access destination table '[SchemaName.TableName]' (Invalid square brackets)

### ISSUE THREAD

**Issue by maxiar** [phongnguyend/EntityFrameworkCore.SqlServer.SimpleBulks#17]
Hi! Excelent works with your library! but when execute  a BulkInsert basic without parameters....
I get this error "Error Cannot access destination table '[SchemaName.TableName]'"  but the schema and table name exists.
I debug your code and the the problem is the "[]" brackets around the [SchemaName.TableName], see the next example:

<img width="716" alt="image" src="https://github.com/phongnguyend/EntityFrameworkCore.SqlServer.SimpleBulks/assets/974115/61c92014-0de9-4725-8f37-0300bada9f81">

SELECT * FROM [vad.VadeResults] --> It is not work (Current Behavior)

SELECT * FROM vad.VadeResults --> It's Works (Expected)
SELECT * FROM [vad].[VadeResults] --> It's Works (Expected Better)
 
I thinks that the expression to complete the "DestinationTableName" property must be something like that [SchemaName].[TableName] to be compatible with differents schemas, and also avoid tables with reserved words... 

As Workaround, I remove the brackets concatenation from this code, and works fine:

<img width="524" alt="image" src="https://github.com/phongnguyend/EntityFrameworkCore.SqlServer.SimpleBulks/assets/974115/acdffab8-fa6d-44b5-ab1b-072364ca26ee">

Thanks in advanced!

**Comment by phongnguyend** [comment]
Thanks for reporting this @maxiar 
I haven’t tested with custom schema yet, will take a look at that.

**Comment by phongnguyend** [comment]
I've released a new version (v6.9.0) which now supports table that has schema name, so this issue should be gone now, could you help to doublecheck @maxiar ?
Thanks

**Comment by maxiar** [comment]
Hi Mr! Sorry I forgot this message! I downloaded the v6.9.0 and works fine! Thanks in advanced!
