### ISSUE TITLE
Get the generated identity value for BulkMerge

### ISSUE THREAD

**Issue by manutiedra** [phongnguyend/EntityFrameworkCore.SqlServer.SimpleBulks#18]
First I want to thank you for this **excellent project**. It works great and it is really fast.

The only thing I'd love to have is to be able to get the entities updated with the PK when I call BulkMerge. With BulkInsert I can get the PK using the ```options.KeepIdentity = false``` but there is no equivalent property for BulkMerge. It would be awesome if that can be added.

**Comment by phongnguyend** [comment]
This feature is now supported and enabled by default in v6.11.0 https://github.com/phongnguyend/EntityFrameworkCore.SqlServer.SimpleBulks/releases/tag/releases%2Fv6.11.0
